### ISSUE TITLE
IPA and withdrawn symbols

### ISSUE THREAD

**Issue by moyogo** [r12a/pickers#1]
It would be good to remove or put aside withdrawn symbols from the IPA picker. Considering there are many more withdrawn or non-standard IPA symbols, it may make more sense to have a separate non-standard section.

After the Kiel Convention of 1989, the ligature affricates were withdrawn from the IPA, instead
the *Report on the 1989 Kiel Convention* (https://doi.org/10.1017/S0025100300003868) indicates the following:
> Affricates can be written by combining the symbol for a plosive and a homorganic fricative, such as [ts] or [kx]. In a language where this is ambiguous for a consonant sequence the two symbols should be joined by a tie bar.

The ligature affricates have not been in the IPA chart since then.

While the voiceless implosives ƥ, ƭ, ƈ, ƙ, ʠ were add to the IPA in 1989, they were withdrawn in 1993 in *Council actions on revisions of the IPA* (https://doi.org/10.1017/S002510030000476X):
> The symbols [ƥ, ƭ, ƈ, ƙ, ʠ] were clearly controversial when presented at the Kiel Convention. A clear majority of the Council voted in favor of proposal 1, withdrawing recognition from [ƥ, ƭ, ƈ, ƙ, ʠ].

**Comment by r12a** [comment]
d͡ʒ  can be obtained from the picker by clicking (or now by typing ~d_0z0), and of course dʒ similarly. I could add the sequence as a single click if needed, but i don't think anyone has asked for it. Same goes for others.  I keep the precomposed ʤ available in the picker because i find it useful, and prefer it for my transliterations because it's more compact.

This picker seems to be widely used, but by phoneticians, rather than necessarily amateurs (who i suspect would be better served by the Latin picker). I'm rather relying on phoneticians to pick what they want from the tool, and ignore the rest.  I suppose i could colour the deprecated symbols differently to alert novice users(?) 

I must admit that i'm rather curious about why the IPA opted for this more complicated way of representing these sounds, but i'm not inclined to pay the cost of obtaining the document to find out :(.

**Comment by moyogo** [comment]
> I must admit that i'm rather curious about why the IPA opted for this more complicated way of representing these sounds, but i'm not inclined to pay the cost of obtaining the document to find out :(.

For consistency with other affricates or doubly-articulated segments.
Instead of creating new ligatures for kx, nɱ, kp, gb, etc. all these can be written by the sequence of the symbols or that sequence with the tie bar if ambiguous.

**Comment by r12a** [comment]
I see. Thanks.

**Comment by HughP** [comment]
@r12a the current IPA chart is at: https://www.internationalphoneticassociation.org/content/full-ipa-chart the app currntly has an link pointing to an old location before the assiciation got its own domain address.

**Comment by r12a** [comment]
Thanks @HughP.  I think that link is in the help page.  I changed the link for all 3 IPA apps.

**Comment by r12a** [comment]
I finally got around to moving the voiceless implosives to a hidden area, so i think this can be closed now.

**Comment by moyogo** [comment]
Thank you @r12a. Should the same be applied to the IPA2 and IPA3 pickers?
