### ISSUE TITLE
[hebrew picker]  Rare Characters not working

### ISSUE THREAD

**Issue by alex-cres** [r12a/pickers#25]
The Diacritics presented in the rare characters tab are all bunched up into one and cannot be picked individually.
![imagem](https://user-images.githubusercontent.com/20164692/29496063-e42ee346-85c2-11e7-9836-f1172f124ffc.png)

**Comment by r12a** [comment]
@alex-cres after a short tussle with github, this should now be fixed. You should clear your cache of the old version, and then go to "more controls/Reset" and click on it.

The dotted circles are gone, because they caused problems with some fonts :(, but the diacritics should be clear and separate enough.

![screen shot 2017-08-22 at 12 37 41](https://user-images.githubusercontent.com/4839211/29563717-bef3a722-8736-11e7-9bbe-b18fcea859c1.png)

thanks for reporting the problem. Reopen this if you are still struggling with this problem.
