### ISSUE TITLE
[khmer picker] Change picker font

### ISSUE THREAD

**Issue by olivierberten** [r12a/pickers#49]
It would be useful for khmer to be able to change the font of the picker. Khmer has 3 styles wich have different shapes for some letters (ក, គ, ង, ជ, ដ, ទ, ន, វ).

The regular style, named chrieng (slanted) or chhor (straight) is the normal text font. The usual title style is named khom, but most people nowadays call it mool (fonts `Khmer Mool` or `Khmer OS Muol`, for instance). The last one, not very much used nowadays is the actual mool style (font `Khmer OS Muol Pali`).

**Comment by r12a** [comment]
@olivierberten I'm guessing that you want to change the font for the selection area, rather than the font of the text added to the large box(?).  To do so, go to `more controls/Change UI font`, where you can select from a variety of fonts.  If there's a font i should add to the list, let me know, since (unlike the font setting for the text area) it's not currently possible to add another font yourself to that control - i should probably make that possible).

Does that solve your problem?

**Comment by olivierberten** [comment]
Oops... I had missed that option... That's indeed what I meant.

Maybe you could add a mool font like [Moul Pali](https://fonts.google.com/specimen/Moulpali) or one of its ancestors [Khmer OS Muol Pali](https://sourceforge.net/projects/khmer/files/Fonts%20-%20KhmerOS/KhmerOS%20Fonts%205.0-%20LGPL%20Licence/) or [Kh Muol Pali](https://sourceforge.net/projects/khmer/files/Fonts%20-%20KhmerOS/Kh%20Uni%20fonts%20for%20design%20pro./).

**Comment by r12a** [comment]
@olivierberten instead of adding those fonts to the set list (though i may still do so in the future), i reworked the way fonts are handled in the pickers. It's now possible to specify and edit your own list of local fonts and they will be added to the end of the preset list.

For more information, see https://r12a.github.io/pickers/khmer/help/#manage_fonts

(Btw, i recommend reading through that whole page at least once.)

Hope that helps. I'm closing this issue, but feel free to reopen if needed.
