### ISSUE TITLE
[ipa picker] character hints make app unusable

### ISSUE THREAD

**Issue by drammock** [r12a/pickers#60]
Here's an example of what I consider a serious regression in the usability of the IPA picker:

I'm trying to get the following sequence: 006c,033a,0020,0279,003a into my clipboard. In other words, lowercase L, apical diacritic, space, lowercase turned R, another apical diacritic.  In past versions of the app, I could type the `l` with my keyboard, pick the diacritic with my mouse, type a space, then pick the last two with my mouse. Then, Ctrl+a to select all, Ctrl+c to copy.  Now if I type `l` and then pick the diacritic with mouse, the hints don't go away, and pressing spacebar changes what I've entered from `l̺` to `lɬ `. Moreover, Ctrl+c to copy simply inserts `c` in place of the selected text, and Ctrl+z to undo (which used to work I think?) now inserts a `z`.  I did figure out that I can get what I need by using the mouse to pick the `l` instead of the keyboard (which won't trigger the hints), and using the "select all" and "copy" buttons (again with the mouse).  Using the mouse for everything, however, is both slower and ergonomically not great.

The hints are a great idea, but need some fine-tuning.  Can we have the old version back please, until these UI/UX issues are worked out?

**Comment by drammock** [comment]
cross-reference to #58 which also mentions the Ctrl+c problem. FWIW, I'm on Linux, not Windows like the OP of that issue.

**Comment by drammock** [comment]
EDIT: just realized that ordinary `l` character is one of the hints, so I can press `l2` to get an ordinary `l` without using the mouse.  In light of this, some suggestions:

- the character sent by the keystroke should always be the first option in the list of hints.
- the hints should be numbered starting with 1, not 0, for better correspondence with the position of numbers on the keyboard --- to select the *leftmost* hinted option, I shouldn't need to press the *rightmost* numeral on my keyboard.
- entering another character/diacritic/modifier letter via the mouse should cancel the current list of hints.  If I've entered a diacritic already, the app should assume I didn't want one of the hinted variants

**Comment by r12a** [comment]
Thanks for the detailed report. I'll look into this.  Btw, if you want to turn off the type assist feature in the meantime, just hit the ` key or click on the T in the vertical grey bar.

**Comment by r12a** [comment]
I ended up rewriting pretty much all the code for the type-assist methods. I'll commit the changes once i've been able to make the necessary updates and checks for all the pickers (small changes needed to default.js), and completed testing the new approach.  Because it's not backwards compatible, i can't release the IPA app until then, although it's working for me locally.

The functionality has changed for the user:

- For the default type-assist input, Latin-based apps (such as the IPA ones) will usually add the typed character to the text area and make no changes unless a different character is picked from the selection list.
- This behaviour is the same for all 'Latin type-assist' features in apps dealing with non-Latin scripts.
- For the default type-assist, non-latin apps will automatically and immediately insert the first item in the selection list when the key is pressed, rather than showing the qwerty key pressed and waiting for another keypress before choosing a substitution, but the initial insertion can of course be overwritten by choosing something else from the selection list, if there are alternatives.  (A selection list appears even if there's only one character in it, since it gives information about transliteraion which may be useful.) 
- Items in the selection list are now ordered from 1 to 0, running from left to right.
- Selection lists should no longer hang around when not needed, and therefore shouldn't produce unexpected results.

I'll post a message here when i commit the changes.

**Comment by drammock** [comment]
Amazing!  Thanks for the quick response.  And thanks for the tip about disabling type-assist hints with backtick in the meantime. Works like a charm, and fixes the Ctrl+a, Ctrl+c, and Ctrl+z problem too.

**Comment by r12a** [comment]
Ah, yes.  The Ctrl+ problem will hopefully be fixed in the upcoming commit, too.  I haven't had a problem with it so far myself, but i can see the logic needed fixing, so i'll be interested to know whether it solved your Linux problem.

**Comment by r12a** [comment]
This should be working now (touch wood). You may need to do a shift-refresh to clear the cache.

**Comment by drammock** [comment]
brilliant, works perfectly, with a minor exception: the "type assist is on..." message doesn't go away when I disable type assist (either by clicking the T, clicking "Clear all", or or using the backtick key. It does go away (replaced by the glyph description text) when I hover over anything in the picker.

**Comment by r12a** [comment]
Ah, that's a relief. Thanks for letting me know!

Yes. The message is a placeholder.  I'll give some thought to ways of improving it.
